//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListHell
{
    using System;
    using System.Collections.Generic;
    
    public partial class ad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ad()
        {
            this.Images = new HashSet<Image>();
            this.Users = new HashSet<User>();
        }
    
        public int adid { get; set; }
        public int catid { get; set; }
        public int lid { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        public virtual Category Category { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
