//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListHell
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.ads = new HashSet<ad>();
        }
    
        public int id { get; set; }
        public string category1 { get; set; }
        public string master_category { get; set; }
        public string category_descr { get; set; }
        public string master_category_descr { get; set; }
        public string editedby { get; set; }
        public Nullable<System.DateTime> editedon { get; set; }
        public string master_category_icon { get; set; }
        public Nullable<int> lid { get; set; }
    
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ad> ads { get; set; }
    }
}
