//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListHell
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public decimal imageid { get; set; }
        public int adid { get; set; }
        public string src { get; set; }
        public Nullable<bool> defaulti { get; set; }
    
        public virtual ad ad { get; set; }
    }
}
